# directory to store cloned antigen repositories
export ADOTDIR=~/dotfiles
export AN_REPOS_DIR=~/dotfiles/repos

# load antigen
source ~/antigen/antigen.zsh

antigen use oh-my-zsh
antigen bundle zsh-users/zsh-syntax-highlighting
antigen-bundle olivierverdier/zsh-git-prompt

source ~/dotfiles/configs/common_profile.zsh

# load the plugins
antigen apply

# The next line updates PATH for the Google Cloud SDK.
if [ -f /home/lihan/google-cloud-sdk/path.zsh.inc ]; then
  source '/home/lihan/google-cloud-sdk/path.zsh.inc'
fi

# The next line enables shell command completion for gcloud.
if [ -f /home/lihan/google-cloud-sdk/completion.zsh.inc ]; then
  source '/home/lihan/google-cloud-sdk/completion.zsh.inc'
fi
