# directory to store cloned antigen repositories
export ADOTDIR=~/dotfiles
export AN_REPOS_DIR=~/dotfiles/repos

# load antigen
source ~/antigen/antigen.zsh

antigen use oh-my-zsh
antigen bundle zsh-users/zsh-syntax-highlighting
antigen-bundle olivierverdier/zsh-git-prompt

source ~/dotfiles/configs/common_profile.zsh

# load the plugins
antigen apply
