# directory to store cloned antigen repositories
export ADOTDIR=~/dotfiles
export AN_REPOS_DIR=~/dotfiles/repos

# load antigen
source ~/antigen/antigen.zsh

antigen use oh-my-zsh
antigen bundle zsh-users/zsh-syntax-highlighting
antigen-bundle olivierverdier/zsh-git-prompt
antigen-bundle zsh-users/zsh-completions

# set fpath for zsh-completions
fpath=($AN_REPOS_DIR/https-COLON--SLASH--SLASH-github.com-SLASH-zsh-users-SLASH-zsh-completions.git/src $fpath)

source ~/dotfiles/configs/common_profile.bash

# load the plugins
antigen apply
