#!/bin/bash
subl_path='/opt/Sublime Text 2/sublime_text'

while getopts ":w" o; do
  case $o in
    w) w=true;;
  esac
done

if [[ $w == true ]]; then
  "$subl_path" $@
else
  nohup "$subl_path" $@ > /dev/null 2>&1 &
fi
