#!/usr/bin/env ruby
require 'mime/types'
require 'base64'

file = ARGV[0]
raise "filename required" if file.nil?
print "url('data:#{MIME::Types.type_for(file)[0]};base64,#{Base64.encode64(IO.read(file)).gsub "\n", ''}')"
